export const GET_ALL_ANNOUNCEMENT_REQUEST = "GET_ALL_ANNOUNCEMENT_REQUEST"
export const GET_ALL_ANNOUNCEMENT_SUCCESS = "GET_ALL_ANNOUNCEMENT_SUCCESS"
export const GET_ALL_ANNOUNCEMENT_FAIL = "GET_ALL_ANNOUNCEMENT_FAIL"

export const DELETE_ANNOUNCEMENT_REQUEST = "DELETE_ANNOUNCEMENT_REQUEST"
export const DELETE_ANNOUNCEMENT_SUCCESS = "DELETE_ANNOUNCEMENT_SUCCESS"
export const DELETE_ANNOUNCEMENT_FAIL = "DELETE_ANNOUNCEMENT_FAIL"

export const UPDATE_ANNOUNCEMENT_REQUEST = "UPDATE_ANNOUNCEMENT_REQUEST"
export const UPDATE_ANNOUNCEMENT_SUCCESS = "UPDATE_ANNOUNCEMENT_SUCCESS"
export const UPDATE_ANNOUNCEMENT_FAIL = "UPDATE_ANNOUNCEMENT_FAIL"

export const CREATE_ANNOUNCEMENT_REQUEST = "CREATE_ANNOUNCEMENT_REQUEST"
export const CREATE_ANNOUNCEMENT_SUCCESS = "CREATE_ANNOUNCEMENT_SUCCESS"
export const CREATE_ANNOUNCEMENT_FAIL = "CREATE_ANNOUNCEMENT_FAIL"

