export const CREATE_COMPLAINT_REQUEST = 'CREATE_COMPLAINT_REQUEST'
export const CREATE_COMPLAINT_FAIL = 'CREATE_COMPLAINT_FAIL'
export const CREATE_COMPLAINT_SUCCESS = 'CREATE_COMPLAINT_SUCCESS'

export const GET_COMPLAINTS_REQUEST = 'GET_COMPLAINTS_REQUEST'
export const GET_COMPLAINTS_SUCCESS = 'GET_COMPLAINTS_SUCCESS'
export const GET_COMPLAINTS_FAIL = 'GET_COMPLAINTS_FAIL'

export const DELETE_COMPLAINT_REQUEST = 'DELETE_COMPLAINT_REQUEST'
export const DELETE_COMPLAINT_FAIL = 'DELETE_COMPLAINT_FAIL'
export const DELETE_COMPLAINT_SUCCESS = 'DELETE_COMPLAINT_SUCCESS'

export const GET_COMPLAINTS_WORKER_REQUEST = 'GET_COMPLAINTS_WORKER_REQUEST'
export const GET_COMPLAINTS_WORKER_SUCCESS = 'GET_COMPLAINTS_WORKER_SUCCESS'
export const GET_COMPLAINTS_WORKER_FAIL = 'GET_COMPLAINTS_WORKER_FAIL'

export const UPDATE_COMPLAINT_SOLVED_REQUEST = 'UPDATE_COMPLAINT_SOLVED_REQUEST'
export const UPDATE_COMPLAINT_SOLVED_SUCCESS = 'UPDATE_COMPLAINT_SOLVED_SUCCESS'
export const UPDATE_COMPLAINT_SOLVED_FAIL = 'UPDATE_COMPLAINT_SOLVED_FAIL'

export const GET_COMPLAINTS_ADMIN_REQUEST = 'GET_COMPLAINTS_ADMIN_REQUEST'
export const GET_COMPLAINTS_ADMIN_SUCCESS = 'GET_COMPLAINTS_ADMIN_SUCCESS'
export const GET_COMPLAINTS_ADMIN_FAIL = 'GET_COMPLAINTS_ADMIN_FAIL'

export const UPDATE_COMPLAINT_ASSIGNED_REQUEST = 'UPDATE_COMPLAINT_ASSIGNED_REQUEST'
export const UPDATE_COMPLAINT_ASSIGNED_SUCCESS = 'UPDATE_COMPLAINT_ASSIGNED_SUCCESS'
export const UPDATE_COMPLAINT_ASSIGNED_FAIL = 'UPDATE_COMPLAINT_ASSIGNED_FAIL'