export const GET_SERVICES_REQUEST = 'GET_SERVICES_REQUEST'
export const GET_SERVICES_FAIL = 'GET_SERVICES_FAIL'
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS'

export const CREATE_SERVICES_REQUEST = 'CREATE_SERVICES_REQUEST'
export const CREATE_SERVICES_FAIL = 'CREATE_SERVICES_FAIL'
export const CREATE_SERVICES_SUCCESS = 'CREATE_SERVICES_SUCCESS'

export const DELETE_SERVICES_REQUEST = 'DELETE_SERVICES_REQUEST'
export const DELETE_SERVICES_FAIL = 'DELETE_SERVICES_FAIL'
export const DELETE_SERVICES_SUCCESS = 'DELETE_SERVICES_SUCCESS'