export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const SUPERVISOR_REGISTER_REQUEST = "SUPERVISOR_REGISTER_REQUEST"
export const SUPERVISOR_REGISTER_SUCCESS = "SUPERVISOR_REGISTER_SUCCESS"
export const SUPERVISOR_REGISTER_FAIL = "SUPERVISOR_REGISTER_FAIL"

export const GET_SUPERVISOR_REQUEST = 'GET_SUPERVISOR_REQUEST'
export const GET_SUPERVISOR_FAIL = 'GET_SUPERVISOR_FAIL'
export const GET_SUPERVISOR_SUCCESS = 'GET_SUPERVISOR_SUCCESS'


export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const UPDATE_USER_ROLE_REQUEST = 'UPDATE_USER_ROLE_REQUEST'
export const UPDATE_USER_ROLE_FAIL = 'UPDATE_USER_ROLE_FAIL'
export const UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS'

export const GET_WORKERS_REQUEST = 'GET_WORKERS_REQUEST'
export const GET_WORKERS_FAIL = 'GET_WORKERS_FAIL'
export const GET_WORKERS_SUCCESS = 'GET_WORKERS_SUCCESS'