export const CREATE_RECORD_REQUEST = 'CREATE_RECORD_REQUEST'
export const CREATE_RECORD_SUCCESS = 'CREATE_RECORD_SUCCESS'
export const CREATE_RECORD_FAIL = 'CREATE_RECORD_FAIL'

export const GET_RECORDS_REQUEST = 'GET_RECORDS_REQUEST'
export const GET_RECORDS_FAIL = 'GET_RECORDS_FAIL'
export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS'

export const UPDATE_WORKER_STATUS_REQUEST = 'UPDATE_WORKER_STATUS_REQUEST'
export const UPDATE_WORKER_STATUS_FAIL = 'UPDATE_WORKER_STATUS_FAIL'
export const UPDATE_WORKER_STATUS_SUCCESS = 'UPDATE_WORKER_STATUS_SUCCESS'